### PR TITLE
Fix crashes caused by notation in lodash require

### PR DESCRIPTION
**Pull request by lemavri**

### CODE REVIEW

**Comment by ce07c3** [comment]
@lemavri thanks for your PR. Which crashes were you encountering? I'd like to reproduce the issue.

The proposed PR unfortunately makes the bundle size grow significantly, I fear.

**Comment by lemavri** [comment]
Hello @ce07c3 ,

I tried with node `v5.4.0` and `v4.2.4` and I'm getting this:

```
mschneider@phobos ♯ 》node index.js
module.js:340
    throw err;
    ^

Error: Cannot find module 'lodash.clonedeep'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/mschneider/Code/node/kisimyapp/node_modules/kisi-client/lib/index.js:1:79)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
```

**Comment by lemavri** [comment]
Also, I believe the function should be `cloneDeep` in case the code is ran in a case-sensitive OS.

**Comment by ce07c3** [comment]
Alright, I'll have a look. Thanks a lot! Should be related to case sensitivity. Using `import cloneDeep from "lodash.clonedeep";` works fine for me, but I am on OS X.

**Comment by lemavri** [comment]
I'm also running OS X, so that might not be the issue. Where are you running `import cloneDeep from "lodash.clonedeep";`?

**Comment by ce07c3** [comment]
On a separate project on OS X - which is why I am wondering where the errors stem from. Maybe different versions?

**Comment by lemavri** [comment]
Are you using that `import` notation on a server-side app? I''ve got to say I'm not very well versed in ES2015, but I think the `import` syntax is not supported out of the box right now in the major browsers nor in the latest version of node unless you use something like [babel](https://babeljs.io/). Also, node.JS's `require` does not behave like the ES2015 `import`. 

I wasn't able to find any example of a dot notation to specify submodules of a package when using `require` in node, which lead me to believe the issue was indeed the syntax in the require.

I guess you could try running the app I wrote using this library to see if you can reproduce the issue: https://github.com/lemavri/kisimyapp (you have to rename the example config file).

**Comment by zachheine** [comment]
Having the same error...

**Comment by KevCron** [comment]
Having same error, created an issue.

**Comment by ce07c3** [comment]
Closed in favor of #18.

**Pull request closed without merging**
